targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/**.dart
        options:
          build_extensions:
            '^lib/{{path}}/{{}}.dart': 'lib/{{path}}/generated/{{}}.g.dart'
      freezed|freezed:
        enabled: true
        options:
          build_extensions:
            '^lib/{{path}}/{{}}.dart': 'lib/{{path}}/generated/{{}}.freezed.dart'
